image: zedctr
org: zededa
network: yes
config:
  binds:
    - /dev:/dev
    - /etc/resolv.conf:/etc/resolv.conf
    - /run:/run
    - /var/config:/config
    - /var/log:/var/log/dom0
    - /:/hostfs
  net: host
  capabilities:
    - all
  pid: host
