required = ["github.com/estesp/manifest-tool"]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/estesp/manifest-tool"
  version = "v0.7.0"
[[override]]
  name = "github.com/docker/docker"
  revision = "7a855799175b6b984886ef1cfa337d6df1d4c668"  
[[override]]
  name = "github.com/docker/distribution"
  revision = "7dba427612198a11b161a27f9d40bb2dca1ccd20"
[[override]]
  name = "github.com/opencontainers/runc"
  revision = "51371867a01c467f08af739783b8beafc15"
[[override]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "1c7c27d043c2a5e513a44084d2b10d77d1402b8c"
